# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 19:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_date', models.DateField(blank=True, null=True)),
                ('attendance', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Id', models.CharField(max_length=10)),
                ('Employee_name', models.CharField(max_length=50)),
                ('Employee_phone', models.CharField(help_text='Phone Number should be 10 digits', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('[0-9]')])),
                ('Employee_email', models.EmailField(max_length=200)),
                ('Employee_Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mentor_Id', models.CharField(max_length=10, unique=True)),
                ('Mentor_name', models.CharField(max_length=49, null=True)),
                ('Mentor_phone', models.CharField(help_text='Phone Number should be 10 digits', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('[0-9]')])),
                ('Mentor_email', models.EmailField(max_length=49, null=True)),
                ('Mentor_Address', models.CharField(max_length=200, null=True)),
                ('Mentor_Gender', models.CharField(help_text='Enter F or M', max_length=10, null=True)),
                ('begining_date', models.DateField(default=django.utils.timezone.now)),
                ('ending_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.CharField(max_length=15, unique=True)),
                ('Student_name', models.CharField(max_length=49)),
                ('Student_curr_grade', models.CharField(max_length=10, null=True)),
                ('Student_prev_grade', models.CharField(max_length=10, null=True)),
                ('Student_Class', models.CharField(max_length=10, null=True)),
                ('Parents_email', models.EmailField(max_length=200, null=True)),
                ('Parents_phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('[0-9]')])),
                ('School', models.CharField(max_length=49)),
                ('Comments', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('Emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empemail', to='home.Employee')),
                ('Men_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Menemail', to='home.Mentor')),
            ],
        ),
        migrations.AddField(
            model_name='classname',
            name='Mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_mentor', to='home.Mentor'),
        ),
        migrations.AddField(
            model_name='classname',
            name='student',
            field=models.ManyToManyField(related_name='class_student', to='home.Student'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Mname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', to='home.Mentor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment2', to='home.Student'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Sname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', to='home.Student'),
        ),
    ]
